---
- name: setup mac
  hosts: all
  vars_files:
    - vars.yml
  tasks:
    # homebrew
    - block:
        - name: install homebrew packages
          homebrew:
            name: "{{ homebrew.packages }}"
            state: present

        - name: install homebrew cask packages
          homebrew_cask:
            name: "{{ homebrew.cask_packages }}"
            state: present
    # user
    - block:
        - name: provision dotfiles
          template:
            src: "{{ item }}.j2"
            dest: "{{ lookup('env','HOME') }}/.{{ item }}"
          loop:
            - zshrc
            - gitconfig

        - name: prepare directories
          file:
            path: "{{ item }}"
            state: directory
          loop:
            - "{{ lookup('env','HOME') }}/.local/share/mc/skins"
            - "{{ lookup('env','HOME') }}/.tmux/plugins"

        # mc
        - name: download dracula theme for mc
          get_url:
            url: https://raw.githubusercontent.com/dracula/midnight-commander/master/skins/dracula256.ini
            dest: "{{ lookup('env','HOME') }}/.local/share/mc/skins/dracula256.ini"

        # tmux
        - name: download tmux plugin manager
          git:
            repo: https://github.com/tmux-plugins/tpm
            dest: "{{ lookup('env','HOME') }}/.tmux/plugins/tpm"
            clone: yes
            update: yes

        - name: setup tmux config
          template:
            src: tmux.conf.j2
            dest: "{{ lookup('env','HOME') }}/.tmux.conf"

        # vim
        - name: prepare vimplug directories
          file:
            path: "{{ lookup('env','HOME') }}/.vim/autoload"
            state: directory
            recurse: True

        - name: install vim-plug
          get_url:
            url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
            dest: "{{ lookup('env','HOME') }}/.vim/autoload/plug.vim"
          when: not ansible_check_mode

        - name: provision .vimrc
          template:
            src: vimrc.j2
            dest: "{{ lookup('env','HOME') }}/.vimrc"

        - name: disable apple press and hold feature
          community.general.osx_defaults:
            domain: NSGlobalDomain
            key: ApplePressAndHoldEnabled
            type: bool
            value: false
            state: present

        - name: enable fast key repeat
          community.general.osx_defaults:
            domain: NSGlobalDomain
            key: KeyRepeat
            type: int
            value: 2
            state: present

        - name: enable fast initial key repeat
          community.general.osx_defaults:
            domain: NSGlobalDomain
            key: InitialKeyRepeat
            type: int
            value: 20
            state: present

        - name: enable vs code key repeat
          community.general.osx_defaults:
            domain: com.microsoft.VSCode
            key: ApplePressAndHoldEnabled
            type: bool
            value: false
            state: present

        # enables Home and End keys in some apps
        - name: setup keybinding directory
          file:
            path: "{{ lookup('env','HOME') }}/Library/KeyBindings"
            state: directory

        - name: setup keybinding dict
          template:
            src: DefaultKeyBinding.dict.j2
            dest: "{{ lookup('env','HOME') }}/Library/KeyBindings/DefaultKeyBinding.dict"

      become_user: "{{ user.login }}"
      become: True
      tags:
        - user

    # renoise
    - block:
        - name: copy FiraCode font file to Renoise app directory
          copy:
            src: FiraCode-Retina.ttf
            dest: /Applications/Renoise.app/Contents/Resources/Skin/Fonts/FiraCode-Retina.ttf

        - name: change Config.xml to use our FiraCode font
          template:
            src: "{{ item }}.j2"
            dest: "/Applications/Renoise.app/Contents/Resources/Skin/Fonts/{{ item }}"
          loop:
            - Config.xml
            - PatternConfig.xml

      become_user: "{{ user.login }}"
      become: True
      tags:
        - renoise
