---
- name: Configure MacOS
  hosts: all
  vars_files:
    - vars.yml
  vars:
    user_home: "{{ lookup('env', 'HOME') }}"
    config_dir: "{{ user_home }}/.config"
    vim_dir: "{{ user_home }}/.vim"
  tasks:
    - name: Import homebrew.yml tasks
      ansible.builtin.import_tasks: tasks/homebrew.yml
      tags:
        - homebrew

    - name: Import user.yml tasks
      ansible.builtin.import_tasks: tasks/user.yml
      tags:
        - user

    - name: Import vim.yml tasks
      ansible.builtin.import_tasks: tasks/vim.yml
      tags:
        - vim

    - name: Import macos_defaults.yml tasks
      ansible.builtin.import_tasks: tasks/macos_defaults.yml
      tags:
        - defaults

    - name: Import sudo.yml tasks
      ansible.builtin.import_tasks: tasks/sudo.yml
      tags:
        - sudo
