---
- name: Configure MacOS
  hosts: all
  vars_files:
    - vars.yml
  vars:
    renoise_font: FiraCode-Regular.ttf
    user_home: "{{ lookup('env', 'HOME') }}"
    config_dir: "{{ user_home }}/.config"
    vim_dir: "{{ user_home }}/.vim"
  tasks:
    - name: Import homebrew.yml tasks
      ansible.builtin.import_tasks: tasks/homebrew.yml

    - name: Import vim.yml tasks
      ansible.builtin.import_tasks: tasks/vim.yml

    - name: Import terminals.yml tasks
      ansible.builtin.import_tasks: tasks/terminals.yml

    - name: Import macos_defaults.yml tasks
      ansible.builtin.import_tasks: tasks/macos_defaults.yml

    - name: Import firewall.yml tasks
      ansible.builtin.import_tasks: tasks/firewall.yml

    - name: Import system.yml tasks
      ansible.builtin.import_tasks: tasks/system.yml

  handlers:
    - name: restart fw
      ansible.builtin.shell: "pfctl -d && pfctl -F all -E -f /etc/pf.conf"
      become: yes
      tags:
        - pf
