---
- name: provision .zshrc
  template:
    src: zshrc.j2
    dest: "{{ lookup('env','HOME') }}/.zshrc"
  tags:
    - user

- name: set font smoothing
  community.general.osx_defaults:
    key: AppleFontSmoothing
    host: currentHost
    type: int
    value: "{{ font_smoothing }}"
    state: present
  tags:
    - user
