---
- block:
    - name: provision dotfiles
      template:
        src: "{{ item }}.j2"
        dest: "{{ lookup('env','HOME') }}/.{{ item }}"
      loop:
        - zshrc
        - gitconfig
      tags:
        - user

    - name: set font smoothing
      community.general.osx_defaults:
        key: AppleFontSmoothing
        host: currentHost
        type: int
        value: "{{ font_smoothing }}"
        state: present
      tags:
        - user

    - name: enable vs code key repeat
      community.general.osx_defaults:
        domain: com.microsoft.VSCode
        key: ApplePressAndHoldEnabled
        type: bool
        value: false
        state: present
      tags:
        - user
  become_user: "{{ user.login }}"
  become: True
