---
- name: provision .zshrc
  template:
    src: zshrc.j2
    dest: "{{ lookup('env','HOME') }}/.zshrc"
  tags:
    - user

- name: download zsh-z plugin
  get_url:
    url: https://raw.githubusercontent.com/agkozak/zsh-z/master/zsh-z.plugin.zsh
    dest: "{{ lookup('env', 'ZSH') }}/custom/plugins/zsh-z.plugin.zsh"
  tags:
    - user

- name: set font smoothing
  community.general.osx_defaults:
    key: AppleFontSmoothing
    host: currentHost
    type: int
    value: "{{ font_smoothing }}"
    state: present
  tags:
    - user
