---
- name: Configure firewall
  become_method: ansible.builtin.sudo
  become_flags: "-i"
  become_user: root
  become: true
  when: pf.enabled is defined and pf.enabled
  block:
    - name: Provision /etc/pf.conf
      ansible.builtin.template:
        src: pf.conf.j2
        dest: /etc/pf.custom.conf
        owner: root
        group: wheel
        mode: 0644
      notify:
        - restart fw

    - name: Provision anchor /etc/pf.anchors/pf.rules
      ansible.builtin.template:
        src: pf.rules.j2
        dest: /etc/pf.anchors/pf.rules
        owner: root
        group: wheel
        mode: 0644
      notify:
        - restart fw
