---
- name: Homebrew
  become_user: "{{ user.login }}"
  become: true
  block:
    - name: Install homebrew packages
      community.general.homebrew:
        name: "{{ homebrew.packages }}"
        state: present

    - name: Install homebrew cask packages
      community.general.homebrew_cask:
        name: "{{ homebrew.cask_packages }}"
        state: present
