---
- name: Terminal setup
  become_user: "{{ user.login }}"
  become: true
  block:
    - name: Prepare directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ user.login }}"
        group: "{{ user.group }}"
        mode: 0700
      loop:
        - "{{ user_home }}/bin"
        - "{{ config_dir }}"
        - "{{ config_dir }}/fish"
        - "{{ config_dir }}/mc"

    - name: Configure scripts
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ user.login }}"
        group: "{{ user.group }}"
        mode: 0500
      loop:
        - { src: scripts/flush-cache.sh.j2, dest: "{{ user_home }}/bin/flush-cache" }

    - name: Configure fish shell
      ansible.builtin.template:
        src: config.fish.j2
        dest: "{{ config_dir }}/fish/config.fish"
        owner: "{{ user.login }}"
        group: "{{ user.group }}"
        mode: 0600

    - name: Configure mc
      ansible.builtin.template:
        src: mc.ini.j2
        dest: "{{ config_dir }}/mc/ini"
        owner: "{{ user.login }}"
        group: "{{ user.group }}"
        mode: 0600

    - name: Configure tmux
      tags:
        - tmux
      block:
        - name: Prepare tmux plugins directory
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            owner: "{{ user.login }}"
            group: "{{ user.group }}"
            mode: 0755
          loop:
            - "{{ user_home }}/.tmux"
            - "{{ user_home }}/.tmux/plugins"
            - "{{ user_home }}/.tmux/plugins/tpm"

        - name: Install tmux tpm
          ansible.builtin.git:
            repo: https://github.com/tmux-plugins/tpm.git
            dest: "{{ user_home }}/.tmux/plugins/tpm"
            version: master

        - name: Configure tmux
          ansible.builtin.template:
            src: tmux.conf.j2
            dest: "{{ user_home }}/.tmux.conf"
            owner: "{{ user.login }}"
            group: "{{ user.group }}"
            mode: 0600

    - name: Configure alacritty
      tags:
        - alacritty
      when:
        - alacritty.enabled is defined
        - alacritty.enabled is true
      block:
        - name: Prepare alacritty directories
          ansible.builtin.file:
            path: "{{ user_home }}/{{ item }}"
            state: directory
            owner: "{{ user.login }}"
            group: "{{ user.group }}"
            mode: 0700
          loop:
            - /.config/alacritty
            - /.config/alacritty/themes

        - name: Download theme from gitlab
          ansible.builtin.get_url:
            url: "https://raw.githubusercontent.com/alacritty/alacritty-theme/master/themes/{{ alacritty.theme }}.yaml"
            dest: "{{ user_home }}/.config/alacritty/themes/{{ alacritty.theme }}.yml"
            owner: "{{ user.login }}"
            group: "{{ user.group }}"
            mode: 0600

        - name: Configure alacritty
          ansible.builtin.template:
            src: alacritty.yml.j2
            dest: "{{ user_home }}/.config/alacritty/alacritty.yml"
            owner: "{{ user.login }}"
            group: "{{ user.group }}"
            mode: 0600

    - name: Configure kitty
      when:
        - kitty.enabled is defined
        - kitty.enabled is true
      tags:
        - kitty
      block:
        - name: Prepare kitty directories
          ansible.builtin.file:
            path: "{{ config_dir }}/kitty"
            state: directory
            owner: "{{ user.login }}"
            group: "{{ user.group }}"
            mode: 0700

        - name: Configure kitty
          ansible.builtin.template:
            src: kitty.conf.j2
            dest: "{{ config_dir }}/kitty/kitty.conf"
            owner: "{{ user.login }}"
            group: "{{ user.group }}"
            mode: 0600
