---
- name: Terminal setup
  become_user: "{{ user.login }}"
  become: true
  block:
    - name: Configure alacritty
      tags:
        - alacritty
      when:
        - alacritty.enabled is defined
        - alacritty.enabled is true
      block:
        - name: Prepare alacritty directories
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            owner: "{{ user.login }}"
            group: "{{ user.group }}"
            mode: 0700
          loop:
            - "{{ config_dir }}/"
            - "{{ config_dir }}/alacritty"
            - "{{ config_dir }}/alacritty/themes"

        - name: Download theme from gitlab
          ansible.builtin.get_url:
            url: "https://raw.githubusercontent.com/alacritty/alacritty-theme/master/themes/{{ alacritty.theme }}.yaml"
            dest: "{{ config_dir }}/alacritty/themes/{{ alacritty.theme }}.yml"
            owner: "{{ user.login }}"
            group: "{{ user.group }}"
            mode: 0600

        - name: Configure alacritty
          ansible.builtin.template:
            src: alacritty.yml.j2
            dest: "{{ config_dir }}/alacritty/alacritty.yml"
            owner: "{{ user.login }}"
            group: "{{ user.group }}"
            mode: 0600

    - name: Configure kitty
      when:
        - kitty.enabled is defined
        - kitty.enabled is true
      tags:
        - kitty
      block:
        - name: Prepare kitty directories
          ansible.builtin.file:
            path: "{{ config_dir }}/kitty"
            state: directory
            owner: "{{ user.login }}"
            group: "{{ user.group }}"
            mode: 0700

        - name: Configure kitty
          ansible.builtin.template:
            src: kitty.conf.j2
            dest: "{{ config_dir }}/kitty/kitty.conf"
            owner: "{{ user.login }}"
            group: "{{ user.group }}"
            mode: 0600
