---
- name: Configure directories, shell and mc
  tags:
    - user
  block:
    - name: Prepare directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ user.login }}"
        group: "{{ user.group }}"
        mode: 0700
      loop:
        - "{{ config_dir }}"
        - "{{ config_dir }}/fish"
        - "{{ config_dir }}/mc"

    - name: Configure fish shell
      ansible.builtin.template:
        src: config.fish.j2
        dest: "{{ config_dir }}/fish/config.fish"
        owner: "{{ user.login }}"
        group: "{{ user.group }}"
        mode: 0600

    - name: Configure fish functions
      ansible.builtin.template:
        src: "fish-functions/{{ item }}.j2"
        dest: "{{ config_dir }}/fish/functions/{{ item }}"
        owner: "{{ user.login }}"
        group: "{{ user.group }}"
        mode: 0600
      loop: "{{ shell.fish_functions }}"
      when:
        - shell.fish_functions is defined
        - shell.fish_functions is iterable

    - name: Configure mc
      ansible.builtin.lineinfile:
        path: "{{ mc.config }}"
        line: "{{ item.key }}={{ item.value }}"
        regexp: "^{{ item.key }}=.+"
        state: present
      loop: "{{ mc.config_lines }}"
      when:
        - mc is defined
        - mc.config_lines is defined
        - mc.config_lines is iterable
        - mc.config is defined

    - name: Configure .gitconfig
      ansible.builtin.template:
        src: gitconfig.j2
        dest: "{{ user_home }}/.gitconfig"
        owner: "{{ user.login }}"
        group: "{{ user.group }}"
        mode: 0644

- name: Configure kitty
  when:
    - kitty.enabled is defined
    - kitty.enabled is true
  tags:
    - kitty
  block:
    - name: Prepare kitty directories
      ansible.builtin.file:
        path: "{{ config_dir }}/kitty"
        state: directory
        owner: "{{ user.login }}"
        group: "{{ user.group }}"
        mode: 0700

    - name: Configure kitty
      ansible.builtin.template:
        src: kitty.conf.j2
        dest: "{{ config_dir }}/kitty/kitty.conf"
        owner: "{{ user.login }}"
        group: "{{ user.group }}"
        mode: 0600

- name: Configure tmux
  tags:
    - tmux
  block:
    - name: Prepare tmux plugins directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ user.login }}"
        group: "{{ user.group }}"
        mode: 0700
      loop:
        - "{{ user_home }}/.tmux"
        - "{{ user_home }}/.tmux/plugins"
        - "{{ user_home }}/.tmux/plugins/tpm"

    - name: Install tmux tpm
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm.git
        dest: "{{ user_home }}/.tmux/plugins/tpm"
        version: master

    - name: Configure tmux
      ansible.builtin.template:
        src: tmux.conf.j2
        dest: "{{ user_home }}/.tmux.conf"
        owner: "{{ user.login }}"
        group: "{{ user.group }}"
        mode: 0600
