---
- name: provision /etc/pf.conf
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: 0644
  notify:
    - restart fw
  tags:
    - pf
    - configure

- name: provision anchor /etc/pf.anchors/pf.rules
  template:
    src: pf.rules.j2
    dest: /etc/pf.anchors/pf.rules
    owner: root
    group: wheel
    mode: 0644
  notify:
    - restart fw
  tags:
    - pf
    - configure

- name: download ip blocklists
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    force: yes
    owner: root
    group: wheel
  loop:
    - { url: https://www.spamhaus.org/drop/edrop.txt, dest: /etc/pf.edrop.txt }
    - { url: https://www.spamhaus.org/drop/drop.txt, dest: /etc/pf.drop.txt }
    - { url: https://lists.blocklist.de/lists/all.txt, dest: /etc/pf.blocklist.de.txt }
  notify:
    - restart fw
  tags:
    - blocklist
    - pf

- name: download ip blocklist from stamparm/ipsum (appear at least on 3 blocklists)
  shell: curl --compressed https://raw.githubusercontent.com/stamparm/ipsum/master/ipsum.txt 2>/dev/null | grep -v "#" | grep -v -E "\s[1-2]$" | cut -f 1 | tee /etc/pf.stamparm.txt
  tags:
    - blocklist
    - pf

- name: replace ; with #
  replace:
    path: "{{ item }}"
    regexp: "; "
    replace: "# "
  loop:
    - /etc/pf.drop.txt
    - /etc/pf.edrop.txt
  notify:
    - restart fw
  tags:
    - blocklist
    - pf

- name: setup launchctl plist
  template:
    src: pf.plist.j2
    dest: /Library/LaunchDaemons/org.{{ lookup('env','USER') }}.pf.plist
    owner: root
    group: wheel
    mode: 0644
  tags:
    - pf
    - configure
