---
packages:
  - cmus
  - curl
  - dos2unix
  - ffmpeg
  - flac
  - fzf
  - gawk
  - git
  - go
  - grep
  - jq
  - lame
  - lua
  - make
  - midnight-commander
  - neovim
  - node
  - pandoc
  - python
  - ripgrep
  - sox
  - sqlite
  - telnet
  - tig
  - tmux
  - tree
  - w3m
  - watch
  - wget
  - xz
  - youtube-dl
  - zsh
  - zsh-completions

cask_packages:
  - blackhole-16ch
  - calibre
  - discord
  - dotnet-sdk
  - firefox
  - fl-studio
  - font-fira-code
  - font-fira-sans
  - google-chrome
  - iterm2
  - keepingyouawake
  - obs
  - signal
  - suspicious-package
  - the-unarchiver
  - vcv-rack
  - visual-studio-code
  - vlc
