---
- name: Check if Homebrew is already installed
  stat:
    path: /opt/homebrew/bin/brew
  register: b

- name: Install Homebrew packages
  homebrew:
    name: "{{ packages }}"
  when: b.stat.exists

- name: Install homebrew cask packages
  homebrew_cask:
    name: "{{ cask_packages }}"
  when: b.stat.exists

- name: Upgrade Homebrew packages
  homebrew:
    upgrade_all: yes
  when: b.stat.exists
