---
- block:
    - name: install homebrew packages
      homebrew:
        name: "{{ homebrew.packages }}"
        state: present

    - name: install homebrew cask packages
      homebrew_cask:
        name: "{{ homebrew.cask_packages }}"
        state: present

  become_user: "{{ user.login }}"
  become: True
  tags:
    - base
