---
- name: install homebrew packages
  homebrew:
    name: "{{ packages }}"
    state: present
  tags:
    - base

- name: install homebrew cask packages
  homebrew_cask:
    name: "{{ cask_packages }}"
    state: present
  tags:
    - base
