---
- name: prepare vimplug directories
  file:
    path: "{{ lookup('env','HOME') }}/.local/share/nvim/site/autoload"
    state: directory
    recurse: yes
  tags:
    - vim

- name: install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ lookup('env','HOME') }}/.local/share/nvim/site/autoload/plug.vim"
  when: not ansible_check_mode
  tags:
    - vim

- name: prepare nvim config directory
  file:
    path: "{{ lookup('env','HOME') }}/.config/nvim"
    state: directory
    recurse: yes
  tags:
    - vim

- name: provision .vimrc
  template:
    src: init.vim.j2
    dest: "{{ lookup('env','HOME') }}/.config/nvim/init.vim"
  tags:
    - vim
    - vimrc
