---
- block:
    - name: prepare vimplug directories
      file:
        path: "{{ lookup('env','HOME') }}/.vim/autoload"
        state: directory
        recurse: True
      tags:
        - vim

    - name: install vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ lookup('env','HOME') }}/.vim/autoload/plug.vim"
      when: not ansible_check_mode
      tags:
        - vim

    - name: provision .vimrc
      template:
        src: vimrc.j2
        dest: "{{ lookup('env','HOME') }}/.vimrc"
      tags:
        - vim
        - vimrc
  become_user: "{{ user.login }}"
  become: True
